name: sourmash_plugin_export
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - sourmash>=4.8.14,<5
  - pip
  - rust==1.81
  - maturin>=1,<2
  - pytest
  - pandas
  - polars
  - compilers
